name: image_carousel
author: Theo Bouwman <theobouwman98@gmail.com>
homepage: https://github.com/theobouwman/flutter_image_carousel
description: A image carousel flutter plugin
version: 0.4.0+1

environment:
  sdk: '>=2.00.0 <3.0.0'

dependencies:
  zoomable_image: '>=1.2.1 <=3.0.0'

  flutter:
    sdk: flutter